### PR TITLE
Controller instrument

### PR DESCRIPTION
**Pull request by RefMags**
- Hello guys: I did the skeletal methods for bookings, instruments and users. 
- In the instruments controller I was trying to work on the method actions, should I work on the rest or we will do it together?

### CODE REVIEW

**Comment by RefMags** [comment]
- Hey, I created a new controller file for owners/bookings and deleted the comments from instruments. 
- I also included pundit. 
- 
**- NB**: don't forget to bundle install after we have made all corrections and merged since pundit is a gem.

**Comment by tom2642** [comment]
Very nice. Please also add the code in Pundit Setup (2) here: https://kitt.lewagon.com/camps/718/lectures/05-Rails%2F07-Airbnb-Facebook-connect#source
and do
rails g pundit:policy instrument
rails g pundit:policy booking
rails g pundit:policy owner/booking

**Comment by RefMags** [comment]
Hey guys, I completed the pundit setup as Tom suggested, please check it out. See you later!!

**Comment by tom2642** [comment]
Very nice. Thanks.

**Pull request merged**
